- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.logined
  path: /
  sameSite: Lax
  secure: false
  value: 'true'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.cs_ind
  path: /
  sameSite: Lax
  secure: false
  value: ''
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.vid
  path: /
  sameSite: Lax
  secure: false
  value: '1688855363420819'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.corpid
  path: /
  sameSite: Lax
  secure: false
  value: '1970325572987152'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.vid
  path: /
  sameSite: Lax
  secure: false
  value: '1688855363420819'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ref
  path: /
  sameSite: Lax
  secure: false
  value: direct
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ltype
  path: /
  sameSite: Lax
  secure: false
  value: '1'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.d2st
  path: /
  sameSite: Lax
  secure: false
  value: a45402
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.refid
  path: /
  sameSite: Lax
  secure: false
  value: '33580490313953'
- domain: .work.weixin.qq.com
  expiry: 1682574774
  httpOnly: false
  name: wwrtx.i18n_lan
  path: /
  sameSite: Lax
  secure: false
  value: zh
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.vst
  path: /
  sameSite: Lax
  secure: false
  value: 7F-u4mQzzYlZM1KbGxP7Ad-i_1PCQn1KnTLLrahZSNjBI-TOX35pvu9y00WwWlW0O12bu93KkjUBsv7rLcpptMa2aHj2SbrmeO-Z5-wmhURGi7IvpPXN7h_ejF27el45AiMgMq0jIWHez4vvW6ngw1p_YbAvl-K-bPPXqrEaXf-B4B9b2C1bTr8AQxUYr60tD_xSzH0FQnZv6KbiTMIG5xZWta7YE-mvamNbY70xFUwrXbGsAPBbimReSnan9GSOqHJ_JQUGWXTVyJHBrrsUvA
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.sid
  path: /
  sameSite: Lax
  secure: false
  value: A-guEqhBVtZXIXCVYEf3cY-gb5uMe9NHRSgrin7zoCzNKhbMmpx36EVrmxUUGqiS
- domain: .work.weixin.qq.com
  expiry: 1711518739
  httpOnly: false
  name: wwrtx.c_gdpr
  path: /
  sameSite: Lax
  secure: false
  value: '0'
